#export(1) lvKRPROD_OpenManual(str,str)
#export(2) lvKRPROD_OpenSupport(str,str)
#export(3) bool lbKRPROD_ConfirmPassword(str,ref str)
#export(4) bool lbKRPROD_ProductDeveloperMode()
#export(5) str lsKRPROD_GetStdCompanyLogoPath(str)
#export(6) lvKRPROD_ProductHomeAddThisPBS(str)
#export(7) bool lbKRPROD_ProductHomeInThisPBS(str)
#export(8) str lsKRPROD_GetProductUnitPath(str)
#export(9) str lsKRPROD_GetLocalProductVersion(str)
