#export(1) bool lbKRST_GetRegEditPropEx(int,str,ref str,str,ref str)
#export(2) str lsKRST_GetRegEditProp(str)
#export(3) bool lbKRST_SetRegEditPropEx(int,str,str,str,ref str)
#export(4) lvKRST_SetRegEditProp(str,str)
#export(5) int liKRST_StringCount(str,str)
#export(6) str lsKRST_SplitStringValue(str,int,str)
#export(7) bool lbKRST_Contains(str,str)
#export(8) str lsKRST_AddCharIfMissing(str,str,bool)
#export(9) str lsKRST_CorrectPath(str)
#export(10) bool lbKRST_FoundInSet(str,str,str)
#export(11) bool lbKRST_ResetUISettings(str,int,str,str,ref str)
#export(12) bool lbKRST_CreateFolderIfNotExists(str,str,ref str)
#export(13) str lsKRST_GetTimeStamp()
#export(14) lvKRST_SelectCbRow(int,str)
#export(15) bool lbKRST_GetCurrentCurrencyRate(int,str,str,ref str,ref str)
#export(16) bool lbKRST_DateInOpenAccountingPeriod(int,str,str,ref str)
#export(17) bool lbKRST_CreateMailByShellExecute(str,str,str,str,str,ref str)
#export(18) bool lbKRST_GetNextLopNoEx(ref str,str,str,str,ref str)
#export(19) lvKRST_SelectSetEd(int,str)
#export(20) int liKRST_FoundInSetPositionEx(str,str,str,str)
#export(21) int liKRST_FoundInSetPosition(str,str,str)
#export(22) bool lbKRST_IsNumeric(str)
#export(24) str lsKRST_ConvertToHTML(str,str)
#export(23) bool lbKRST_StartPTC(str,ref str)
#export(25) str lsKRST_ReplaceStringAtPos(str,str,int,str)
#export(26) str lsKRST_DeleteStringAtPos(str,int,str)
#export(27) str lsKRST_AddStringAfterPos(str,str,int,str)
#export(28) str lsKRST_RemoveCode(str,str,str,str)
#export(29) lvKRST_GetSealInfo(str,ref str,ref str,ref str,ref str)
#export(30) str lsKRST_GetSealMessage(str,str,str)
#export(31) str lsKRST_CreateSeal(str,str,str)
#export(33) str lsKRST_LcFindRows(int,int,str,str,str)
#export(34) str lsKRST_GetFileDate(str,str)
#export(35) str lsKRST_GetFileTime(str,str)
#export(36) str lsKRST_GetFileDateTime(str,str)
#export(37) str lsKRST_GetFileSize(str,str,str)
#export(38) bool lbKRST_FileAccessable(str,ref str)
#export(39) bool lbKRST_PathAccessable(str,ref str)
#export(40) str lsKRST_TextFromRight(str,int,str)
#export(41) str lsKRST_ConvertSecondsToTime(int,str)
#export(42) bool lbKRST_GetCustomerInvoicePath(str,str,ref str,str,ref str)
#export(43) bool lbKRST_GetSupplierInvoicePath(str,str,ref str,str,ref str)
#export(44) str lsKRST_AddCode(str,str,str,str)
#export(45) str lsKRST_BubbleSortString(str,str,bool,str)
#export(46) bool lbKRST_GetRegEditPropKeys(str,ref str,ref int,str,ref str)
#export(47) bool lbKRST_DeleteRegEditProp(str,str,ref str)
#export(48) str lsKRST_GetCbRowCode(int)
#export(49) lvKRST_AddString(ref str,str,str)
#export(50) bool lbKRST_LcDataNumbersVerify(int,str,str,ref str)
#export(51) bool lbKRST_LcGetDataNumberCol(int,int,ref int,str,ref str)
#export(52) int liKRST_LcGetDataNumberCol(int,int)
#export(53) bool lbKRST_LcGetTextSelected(int,int,ref str,str,ref str)
#export(54) str lsKRST_LcGetTextSelected(int,int)
#export(55) bool lbKRST_LcGetTextMulti(int,int,ref str,str,ref str)
#export(56) str lsKRST_LcGetTextMulti(int,int,str)
#export(57) str lsKRST_EstimatedTimeLeft(str,str,int,int,str,str)
