#export(1) lvKRUPP_LogStandard(str)
#export(2) lvKRUPP_LogError(str)
#export(3) lvKRUPP_LogDetailed(str)
#export(4) lvKRUPP_ProductHomeAddThisPBS(str)
#export(5) bool lbKRUPP_ProductHomeInThisPBS(str)
#export(6) bool lvKRUPP_ClearTempFolder(str,str)
#export(7) int liKRUPP_StringCount(str,str)
#export(8) str lsKRUPP_SplitStringValue(str,int,str)
#export(9) bool lbKRUPP_CreateFolderIfNotExists(str,str,ref str)
#export(10) str lsKRUPP_ConvertToHTML(str,str)
#export(11) bool lbKRUPP_FileExtensionCheck(str,str,ref str)
#export(12) bool lbKRUPP_FtpKruppInit(str,str,ref int,ref str)
#export(13) bool lbKRUPP_TransferFtp(str,str,str,str)
#export(14) bool lbKRUPP_FtpKruppClose(ref int,ref str)
#export(15) bool lbKRUPP_CreateUnpackFolder(str,ref str,ref str)
#export(16) bool lbKRUPP_UnpackZip(str,str,ref str)
#export(17) bool lbKRUPP_ReplaceFile(str,str,ref str)
#export(18) str lsKRUPP_GetProductUnitPath(str)
#export(19) str lsKRUPP_GetProductLocalVersionNo(str)
#export(20) str lsKRUPP_GetProductLocalBuild(str)
#export(21) str lsKRUPP_GetProductLocalStartDialog(str)
#export(22) bool lbKRUPP_GetProductLocalBeta(str)
#export(23) bool lbKRUPP_CompatibleVersion(str,str,ref str)
#export(24) str lsKRUPP_GetUnitPathFile(str,str)
#export(25) bool lbKRUPP_FilesMatch(str,str,ref str)
#export(26) bool lbKRUPP_IsDialog(str)
#export(27) bool lbKRUPP_IsLib(str)
#export(28) bool lbKRUPP_IsProg(str)
#export(29) str lsKRUPP_FileDestination(str,str,str,ref str)
#export(30) bool lbKRUPP_ValidateCurrentFile(str,str,str,ref str)
#export(31) lvKRUPP_CreateKruppFolders()
#export(32) str lsKRUPP_DownloadProductImage(int,str)
#export(33) str lsKRUPP_DownloadProductDesc(ref int,str,str)
#export(34) str lsKRUPP_DownloadProductPackVersion(int,str)
#export(35) bool lbKRUPP_ShowBeta(str)
#export(36) bool lbKRUPP_VerifyFilesInFolder(str,str,str,ref str)
#export(37) bool lbKRUPP_UpdateFilesFromFolder(str,str,ref str,str,ref str)
#export(38) str lsKRUPP_GetInstalledUnitPath(str,str,ref str)
#export(39) bool lbKRUPP_NewVersionAvailable(ref int,str,str,str,str,ref str,ref str,ref str,ref str,ref str)
#export(40) bool lbKRUPP_SaveProductInfo(str,str,str,str,str,str,ref str)
#export(41) bool lbKRUPP_SaveProductBetaInfo(str,bool,str,ref str)
#export(42) bool lbKRUPP_Uninstalled(str,str,ref str)
#export(43) bool lbKRUPP_UnpackDSExp(str,str,ref str,ref str)
#export(44) bool lbKRUPP_DownloadBuild(ref int,str,str,ref str,str,ref str)
#export(45) bool lbKRUPP_UpdateProduct(ref int,str,str,str,str,ref str,str,ref str)
#export(46) bool lbKRUPP_CheckFileConflicts(str,str,ref str)
#export(47) bool lbKRUPP_InstallProduct5520(ref int,str,str,str,str,str,ref str)
#export(48) bool lbKRUPP_DownloadCheckFileConflicts(ref int,str,str,str,ref str)
#export(49) bool lbKRUPP_AddUSERMENU(str,int,str,str,str,str,str,str,str,ref str)
#export(50) str lsKRUPP_GetStdCompanyLogoPath(str)
#export(51) str lsKRUPP_GetStdProductImageIconPath()
#export(52) str lsKRUPP_GetStdToolImageIconPath()
#export(53) bool lbKRUPP_FoundInSet(str,str,str)
#export(54) bool lbKRUPP_BackupUnitFolder(str,str,str,str,str)
#export(55) bool lbKRUPP_BackupExecute(str,str,str,ref str)
#export(56) bool lbKRUPP_HasLatestVersion(str,str)
#export(57) lvKRUPP_SplitProductVersion(str,ref str,ref str,ref str)
#export(58) bool lbKRUPP_IsMinorUpdate(str,str)
#export(59) str lsKRUPP_GetExecuteModeDesc(str,str)
#export(60) str lsKRUPP_GetExecuteMode(str,bool,bool,bool,str,str)
#export(61) bool lbKRUPP_DownloadProductList(ref int,str,str,str,ref str)
#export(62) lvKRUPP_TmpTableCreate(str)
#export(63) bool lbKRUPP_TmpLoad(ref int,str,bool,bool,str,ref str)
#export(64) bool lbKRUPP_DownloadAndSetProductImage(ref int,str,int,str,ref str)
#export(65) bool lbKRUPP_DownloadBaseImages(ref int,str,ref str)
#export(66) bool lbKRUPP_TmpChangeProductMode(str,str,ref str)
#export(67) int liKRUPP_TmpUpdateMandatory(ref int,ref str,str,ref str)
#export(68) lvKRUPP_LogCurrentKRUPPVersion()
#export(69) bool lbKRUPP_OpenProductDialog(str,str,ref str)
#export(70) bool lbKRUPP_SelfUpdateDialog(ref int,ref str,str,ref str)
#export(71) bool lbKRUPP_AllPBSAddUSERMENU(int,str,str,str,str,str,str,str,ref str)
#export(72) lvKRUPP_OpenManual(str,str)
#export(73) lvKRUPP_OpenSupport(str,str)
#export(74) bool lbKRUPP_UninstallKrupp(str,ref str)
#export(75) bool lbKRUPP_SavePbsInfo(str,ref str)
#export(76) bool lbKRUPP_UploadPbsInfo(ref int,str,ref str)
#export(77) bool lbKRUPP_UploadKrapBackup(ref int,str,ref str)
#export(78) bool lbKRUPP_SendFeedback(str)
#export(80) bool lbKRUPP_CorrectFileCR(str,str,ref str)
