#export(1) bool lbKRLOG_SetLogLevel(str,str,str,str,ref str)
#export(2) str lsKRLOG_GetLogLevel(int,str,str,str)
#export(3) bool lbKRLOG_SetLogHistory(str,str,str,str,ref str)
#export(4) int liKRLOG_GetLogHistory(int,str,str,str)
#export(5) bool lbKRLOG_ChangeRegistryStatus(int,str,str,str,ref str)
#export(6) lvKRLOG_Standard(str,str,str)
#export(7) lvKRLOG_Detailed(str,str,str,str)
#export(8) lvKRLOG_Error(str,str,str,str,str)
#export(9) lvKRLOG_Trace(str,str)
#export(10) str lsKRLOG_GetLogPathDir(str,str)
#export(11) bool lbKRLOG_EraseHistory(str,str,ref str)
